name: containers host test
on: workflow_dispatch
jobs:
  container-with-host:
    runs-on: ubuntu-latest
    container:
      image: alpine
      options: --add-host example.local:93.184.216.34
    steps:
      - name: Print hosts
        run: cat /etc/hosts
  container-without-host:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Print hosts
        run: cat /etc/hosts
